twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        EntityMGR:  "@EntityMGR"
        Jdate:  "@Jdate"
        ConfigMGR:  "@ConfigMGR"
    form_themes: ['bootstrap_4_layout.html.twig',
                 '@FOSCKEditor/Form/ckeditor_widget.html.twig']